### ISSUE TITLE
Changing the background color for bootstra.386

### ISSUE THREAD

**Issue by robbiefla** [salcode/bootstra.386-genesis#1]
Very simple question, I am not very experienced with coding, I am using WordPress which I have moderate skills with. I simply want to change the background color of the bootstra.386 WordPress theme from the blue background to a black background.  Thanks in advance!

**Comment by salcode** [comment]
@robbiefla 

Two options off the top of my head, the best practice (but complex) and the hacky (easiest).

## Officially Updating the Theme

This is the more difficult, but best practice for long term management of changes to the theme.  It requires adding the necessary build tools (e.g. [npm](https://www.npmjs.com/)) to run the grunt task that takes the scss files and turns them into CSS.  Setup notes can be found in [Gruntfile.js](https://github.com/salcode/bootstra.386-genesis/blob/master/Gruntfile.js).

In this case, you would update [css/sass/supporting/bootstrap.scss](https://github.com/salcode/bootstra.386-genesis/blob/master/css/sass/supporting/bootstrap.scss) changing the color on [line 238](https://github.com/salcode/bootstra.386-genesis/blob/master/css/sass/supporting/bootstrap.scss#L238) from `#000084` to `#000000`

Then run

```
grunt prod
```

from the command line, which generates output like the following

```
Running "sass:prod" (sass) task
File "css/style.min.css" created.

Running "uglify:prod" (uglify) task
File "js/javascript.min.js" created.
```

and now the theme should be updated with the black background color.

## Quick and Dirty

Using the [WordPress Theme Customizer](https://premium.wpmudev.org/blog/wordpress-theme-customizer-guide/), under the **Additional CSS** option, you can add

```
body { background-color: #000000; }
```

Technically, this doesn't actually make any change to your theme but instead adds extra CSS in WordPress that overwrites the background color with our new color `#000 (black).

I hope these help.

![screen shot 2018-07-05 at 15 28 44](https://user-images.githubusercontent.com/5194588/42343788-27da4428-8068-11e8-838d-69bf7a6c5755.png)

**Comment by robbiefla** [comment]
That was an easy fix! Thank you for the quick response!
