### ISSUE TITLE
DOS cursor movement

### ISSUE THREAD

**Issue by robbiefla** [salcode/bootstra.386-genesis#2]
When making a change to my website using the bootstra.386 theme in WordPress, if I make a change and test the change the DOS cursor flows down the screen as designed. When actually going to the site and observing the website, the DOS cursor never shows. I have refreshed the browser, tried another browser and even tried another computer, in WordPress you see the cursor activity, in the browser you do not.

Any ideas?

**Comment by salcode** [comment]
If I understand correctly, when loading the site in the [Customizer](https://premium.wpmudev.org/blog/wordpress-theme-customizer-guide/) (e.g. https://genesis.test/wp-admin/customize.php), the cursor flows down screen but when loaded as a normal page (https://genesis.test), whether logged in or not, the cursor flow does not occur.

This error does appear in the Chrome console

> Uncaught TypeError: $ is not a function at javascript.min.js?ver=1.4:1

<img width="572" alt="screen shot 2018-07-06 at 16 56 54" src="https://user-images.githubusercontent.com/5194588/42399935-ae69e6e4-813d-11e8-8093-d38a8a7c3618.png">

I suspect this is the root of the problem. 

When I get a chance, I'll dig in to this and either change `$` to `jQuery` or set `var $ = jQuery;` somewhere before the code throwing the error, which I expect should correct the issue.

**Comment by robbiefla** [comment]
Awesome! Thanks again for your help!

**Comment by salcode** [comment]
This is fixed and the corrected code is in release [v1.5.0](https://github.com/salcode/bootstra.386-genesis/releases/tag/v1.5.0)
